defmodule StateServer.Autogen do
  @moduledoc false

  # this is just a behaviour module which describes the auto-generated
  # functions created by the `use StateServer` directive.  These should
  # be separate out so that someone can create an implementation of
  # state server while using the rest of it as a 'shim'

  @doc """
  an autogenerated guard which can be used to check if a state is terminal
  """
  @macrocallback is_terminal(state::atom) :: Macro.t

  @doc """
  an autogenerated guard which can be used to check if a state and transition
  will lead to a terminal state.
  """
  @macrocallback is_terminal_transition(state::atom, transition::atom) :: Macro.t

  @doc """
  an autogenerated guard which can be used to check if a state and transition
  will lead to any state.
  """
  @macrocallback is_edge(state::atom, transition::atom, dest::atom) :: Macro.t
end
